"""BUILD the deployable course site, in every locale.

Run:  python3 build_site.py

Three jobs:

  1. NAVIGATION. Injects a slim nav bar into every page, between idempotent
     markers, so the build can be re-run without duplicating anything. The bar
     carries home, this page's position, its neighbours by name, and a language
     switcher.

     The nav lives in its OWN stylesheet. Six of the twelve English pages predate
     page.css and carry inline <style> blocks instead, so anything appended to
     page.css would silently miss half the site.

  2. LOCALES. English pages live at the repository root; a translation lives in
     <code>/ (e.g. ru/). Only pages that have actually been translated go into
     that locale's output. Its contents page links plainly to `x.html`, and this
     build REWRITES that to `../x.html` when no translation exists yet, so an
     untranslated entry falls back to the English page instead of 404ing. That
     rewrite is why translating a page later needs no bookkeeping: drop the file
     in ru/ and the link stops being rewritten.

  3. A CLEAN docs/. Copies each page plus only the assets that page actually
     references, resolved from its own <script src> and <link href> tags. The
     repository holds a 26 MB download cache, the measurement scripts and sixteen
     verification scripts -- none of which may ship. The rule is an ALLOWLIST
     built from the pages themselves, not a denylist of things to skip, because a
     denylist silently ships whatever it forgot.

     Each locale directory is SELF-CONTAINED -- it gets its own copy of the
     assets -- so every asset link stays flat and no page needs `../` to load a
     stylesheet. At ~580 KB a copy that is a trivial price for the simplicity.

GitHub Pages can publish a branch's root or /docs and nothing else, which is why
the output directory is called docs/. The name is that convention, not a
description.
"""
from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "docs"

NAV_BEGIN = "<!-- NAV:BEGIN generated by data/build_site.py — do not hand-edit -->"
NAV_END = "<!-- NAV:END -->"

FORBIDDEN = re.compile(r"(^|/)(\.attic|data|docs|dist|__pycache__)(/|$)|\.py$")

# Every locale the site is built in. `src` is the source directory relative to
# the repository root; `out` is the directory inside docs/. English is first and
# is the fallback for anything a translation has not covered yet.
LOCALES = [
    dict(code="en", label="EN", src=".", out=".", lang="en",
         count="{n} visuals · every figure checked against its data",
         start="start", of="{i} of {n}", home="UDJ"),
    dict(code="ru", label="RU", src="ru", out="ru", lang="ru",
         count="{n} визуализаций · каждая цифра сверена с данными",
         start="начать", of="{i} из {n}", home="UDJ"),
]


def src_dir(loc: dict) -> Path:
    return ROOT if loc["src"] == "." else ROOT / loc["src"]


def out_dir(loc: dict) -> Path:
    return OUT if loc["out"] == "." else OUT / loc["out"]


# --------------------------------------------------------------- the manifest
def manifest(loc: dict) -> list[dict]:
    """The running order, read from that locale's own contents page."""
    p = src_dir(loc) / "index.html"
    if not p.exists():
        raise SystemExit(f"{loc['code']}: no index.html in {p.parent}")
    s = p.read_text(encoding="utf-8")
    out = []
    for m in re.finditer(
        r'<li><a href="(?:\.\./)?([a-z]+\.html)">\s*'
        r'<span class="n">([^<]+)</span>\s*'
        r'<span class="t">([^<]+?)\s*<span class="d">',
        s,
    ):
        out.append(dict(href=m.group(1), num=m.group(2).strip(),
                        title=re.sub(r"\s+", " ", m.group(3)).strip()))
    if not out:
        raise SystemExit(f"{loc['code']}: could not read the running order")
    return out


# --------------------------------------------------------------------- nav CSS
NAV_CSS = """/* GENERATED by data/build_site.py — do not hand-edit.
   The nav's own stylesheet. It cannot live in page.css: six of the twelve
   English pages predate that file and carry inline <style> blocks, so half the
   site would miss it. Every colour carries a literal fallback so the bar still
   renders if tokens.css is absent. */
.sitenav {
  position: sticky; top: 0; z-index: 60;
  display: flex; align-items: center; gap: 18px;
  padding: 10px 22px;
  background: rgba(5, 7, 13, 0.92);
  border-bottom: 1px solid var(--line, rgba(140, 170, 210, 0.14));
  backdrop-filter: blur(8px);
  font-family: var(--mono, ui-monospace, "SF Mono", Menlo, monospace);
  font-size: 11px; letter-spacing: 0.06em;
}
.sitenav a { text-decoration: none; }
.sn-home {
  font-weight: 700; letter-spacing: 0.16em;
  color: var(--fg, #e2eefc); opacity: 0.9; white-space: nowrap;
}
.sn-home:hover { opacity: 1; color: var(--cyan, #8ae1f5); }
.sn-pos {
  color: var(--cyan, #8ae1f5); opacity: 0.85; white-space: nowrap;
  padding-left: 14px; border-left: 1px solid rgba(140, 170, 210, 0.18);
}
.sn-count { color: var(--dim, rgba(150, 180, 220, 0.5)); white-space: nowrap; }
.sn-links { margin-left: auto; display: flex; align-items: center; gap: 14px;
            min-width: 0; }
.sn-prev, .sn-next {
  color: var(--dim, rgba(150, 180, 220, 0.62));
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  max-width: 30ch;
}
.sn-prev:hover, .sn-next:hover { color: var(--cyan, #8ae1f5); }
.sn-next { font-weight: 600; color: rgba(190, 214, 240, 0.85); }
/* language switcher */
.sn-lang {
  display: flex; align-items: center; gap: 6px; white-space: nowrap;
  padding-left: 14px; border-left: 1px solid rgba(140, 170, 210, 0.18);
}
.sn-lang a, .sn-lang span {
  padding: 2px 6px; border-radius: 4px; letter-spacing: 0.12em;
  font-weight: 600; font-size: 10px;
}
.sn-lang a { color: var(--dim, rgba(150, 180, 220, 0.55)); }
.sn-lang a:hover { color: var(--cyan, #8ae1f5);
                   background: rgba(138, 224, 244, 0.10); }
.sn-lang .on {
  color: #05070d; background: var(--cyan, #8ae1f5);
}
@media (max-width: 980px) { .sn-prev { display: none; } }
@media (max-width: 860px) {
  .sitenav { gap: 10px; padding: 8px 14px; font-size: 10px; }
  .sn-count { display: none; }
  .sn-next { max-width: 18ch; }
}
@media (prefers-reduced-motion: reduce) {
  .sitenav { backdrop-filter: none; background: #05070d; }
}
"""


def lang_switch(loc: dict, href: str, translated: dict[str, set[str]]) -> str:
    """EN | RU. Each inactive locale links to its counterpart of THIS page when
    that translation exists, and to its contents page when it does not -- never
    to a URL that would 404."""
    bits = []
    for other in LOCALES:
        if other["code"] == loc["code"]:
            bits.append(f'<span class="on">{other["label"]}</span>')
            continue
        # path from this locale's directory to the other locale's directory
        up = "" if loc["out"] == "." else "../"
        down = "" if other["out"] == "." else f'{other["out"]}/'
        target = href if href in translated[other["code"]] else "index.html"
        bits.append(f'<a href="{up}{down}{target}">{other["label"]}</a>')
    return '<span class="sn-lang">' + "".join(bits) + "</span>"


def nav_html(loc: dict, order: list[dict], i: int | None,
             href: str, translated: dict[str, set[str]]) -> str:
    """i is the index in `order`, or None for the contents page itself."""
    n = len(order)
    switch = lang_switch(loc, href, translated)
    if i is None:
        first = order[0]
        body = (
            f'<a class="sn-home" href="index.html">{loc["home"]} · '
            f'{"SEEING THE STATISTICS" if loc["code"] == "en" else "УВИДЕТЬ СТАТИСТИКУ"}</a>'
            f'<span class="sn-count">{loc["count"].format(n=n)}</span>'
            f'{switch}'
            f'<span class="sn-links">'
            f'<a class="sn-next" href="{first["href"]}">{loc["start"]} · '
            f'{first["num"]} {first["title"]} →</a></span>'
        )
    else:
        cur = order[i]
        links = ""
        if i > 0:
            p = order[i - 1]
            links += (f'<a class="sn-prev" href="{p["href"]}">← {p["num"]} '
                      f'{p["title"]}</a>')
        if i < n - 1:
            q = order[i + 1]
            links += (f'<a class="sn-next" href="{q["href"]}">{q["num"]} '
                      f'{q["title"]} →</a>')
        body = (
            f'<a class="sn-home" href="index.html">← {loc["home"]}</a>'
            f'<span class="sn-pos">{cur["num"]} · {cur["title"]}</span>'
            f'<span class="sn-count">{loc["of"].format(i=i + 1, n=n)}</span>'
            f'{switch}'
            f'<span class="sn-links">{links}</span>'
        )
    return f'{NAV_BEGIN}\n<nav class="sitenav">{body}</nav>\n{NAV_END}'


# ------------------------------------------------------------------- injection
def inject(text: str, nav: str, name: str) -> str:
    s = text
    if NAV_BEGIN in s:
        s = re.sub(re.escape(NAV_BEGIN) + r".*?" + re.escape(NAV_END), nav, s,
                   count=1, flags=re.S)
    else:
        m = re.search(r"^<body>\s*$", s, re.M)
        if not m:
            raise SystemExit(f"{name}: no plain <body> line to inject after")
        s = s[:m.end()] + "\n" + nav + s[m.end():]

    if 'href="nav.css"' not in s:
        m = re.search(r'(<link rel="stylesheet" href="[^"]+">)(?![\s\S]*'
                      r'<link rel="stylesheet")', s)
        if m:
            s = s[:m.end()] + '\n<link rel="stylesheet" href="nav.css">' + s[m.end():]
        else:
            s = s.replace("</head>", '<link rel="stylesheet" href="nav.css">\n</head>', 1)
    return s


def assets_of(html: str) -> list[str]:
    """Local files a page loads. Allowlist: only what the page names itself."""
    found = []
    for m in re.finditer(r'<(?:script|link)[^>]*?(?:src|href)="([^"]+)"', html):
        u = m.group(1)
        if u.startswith(("http://", "https://", "//", "#", "data:", "mailto:")):
            continue
        if u.endswith(".html"):
            continue
        if FORBIDDEN.search(u) or ".." in u:
            raise SystemExit(f"a page references a forbidden path: {u!r}")
        found.append(u)
    return found


def fallback_links(html: str, have: set[str]) -> tuple[str, int]:
    """Rewrite `href="x.html"` to `../x.html` for pages this locale has not
    translated, so an untranslated entry falls back to English rather than
    404ing. Idempotent: an already-rewritten link is left alone."""
    n = 0

    def sub(m):
        nonlocal n
        pre, page = m.group(1), m.group(2)
        if page in have or pre:
            return m.group(0)
        n += 1
        return f'href="../{page}"'

    return re.sub(r'href="(\.\./)?([a-z]+\.html)"', sub, html), n


def main() -> None:
    # which pages each locale has actually translated
    translated: dict[str, set[str]] = {}
    for loc in LOCALES:
        d = src_dir(loc)
        translated[loc["code"]] = {
            p.name for p in d.glob("*.html")
        } if loc["src"] != "." else {p.name for p in ROOT.glob("*.html")}

    (ROOT / "nav.css").write_text(NAV_CSS, encoding="utf-8")
    print("wrote nav.css")

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir()

    summary = []
    for loc in LOCALES:
        order = manifest(loc)
        have = translated[loc["code"]]
        d, o = src_dir(loc), out_dir(loc)
        o.mkdir(parents=True, exist_ok=True)
        print(f"\n=== {loc['code']} — {len(order)} entries, "
              f"{len(have)} page(s) present ===")

        pages = [("index.html", None)]
        for i, e in enumerate(order):
            if e["href"] in have:
                pages.append((e["href"], i))

        needed: set[str] = {"nav.css"}
        for href, i in pages:
            src = d / href
            original = src.read_text(encoding="utf-8")
            nav = nav_html(loc, order, i, href, translated)

            # ORDER MATTERS: inject the nav FIRST, then rewrite fallback links.
            # Done the other way round, the nav's own start/prev/next links point
            # at untranslated pages with no `../` and 404. The verification
            # caught exactly that.
            text, nrw = fallback_links(inject(original, nav, href), have)
            (o / href).write_text(text, encoding="utf-8")
            needed.update(assets_of(text))

            # The SOURCE keeps plain links -- it is the canonical copy, and the
            # `../` resolution is a property of the built output, not of the
            # page. It does get the nav, so browsing the repo shows the same
            # navigation the site has.
            src.write_text(inject(original, nav, href), encoding="utf-8")
            if nrw:
                print(f"  {href}: {nrw} link(s) fall back to English")

        for a in sorted(needed):
            asrc = d / a
            if not asrc.exists():
                asrc = ROOT / a          # shared asset, not locale-specific
            if not asrc.exists():
                raise SystemExit(f"{loc['code']} references {a!r}, which is missing")
            (o / a).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(asrc, o / a)

        print(f"  {len(pages)} page(s) + {len(needed)} asset(s) -> "
              f"{o.relative_to(ROOT)}/")
        summary.append(dict(locale=loc["code"], pages=len(pages),
                            entries=len(order), assets=len(needed),
                            order=[dict(order=i + 1, **e)
                                   for i, e in enumerate(order)]))

    total = sum(f.stat().st_size for f in OUT.rglob("*") if f.is_file())
    nfiles = sum(1 for f in OUT.rglob("*") if f.is_file())
    print(f"\ndocs/ — {nfiles} files, {total / 1024:.0f} KB")

    (OUT / "manifest.json").write_text(json.dumps(
        dict(locales=summary, bytes=total, files=nfiles), indent=1,
        ensure_ascii=False), encoding="utf-8")

    en = summary[0]
    (OUT / "README.md").write_text(f"""# Seeing the statistics — deployable bundle

{en['entries']} interactive statistics visuals plus a contents page, in
{len(LOCALES)} locale(s). Generated by `data/build_site.py`; do not edit anything
here by hand, it is overwritten.

The directory is called `docs/` because GitHub Pages can publish a branch's root
or `/docs` and nothing else. The name is that convention, not a description.

## Locales

| Code | Path | Pages translated |
|---|---|---|
""" + "\n".join(
        f"| `{s['locale']}` | `{'/' if s['locale'] == 'en' else '/' + s['locale'] + '/'}` "
        f"| {s['pages']} of {s['entries'] + 1} |" for s in summary) + f"""

A locale carries only the pages actually translated for it. Its contents page
links to the English page for anything not yet done, so no entry 404s.

## Deploying

Entirely static — no server-side anything, no build step at the far end, and
every internal link is relative, so it works from a subdirectory as well as a
domain root.

    # GitHub Pages — Settings > Pages > Source: branch, folder /docs
    # (no workflow needed; committing this folder is the deploy)

    # any other static host
    aws s3 sync . s3://your-bucket/ --delete
    netlify deploy --prod --dir .

## One external dependency

The pages load **Manrope** and **Inter** from Google Fonts, both of which carry
Cyrillic, so the Russian pages get the same typeface as the English ones. Without
network access the type falls back to a system stack and the layout still holds.
For a fully offline bundle, vendor the two font files and rewrite the `<link>`
tags.

## What is deliberately absent

The source repository also holds a 26 MB dataset download cache, the scripts that
measure the data, and sixteen verification scripts that re-derive every published
figure from its raw source. None of that is needed to serve the site, so none of
it is here. `docs/` is assembled from an allowlist built by reading each page's
own asset tags — not by copying the repository and deleting things.
""", encoding="utf-8")
    print("wrote docs/manifest.json and docs/README.md")


if __name__ == "__main__":
    main()
