"""BUILD the deployable course site.

Run:  python3 build_site.py

Two jobs:

  1. NAVIGATION. Injects a slim nav bar into every page, between idempotent
     markers, so the build can be re-run without duplicating anything. The bar
     carries home, this page's position, and its neighbours by name.

     The nav lives in its OWN stylesheet. Six of the twelve pages predate
     page.css and carry inline <style> blocks instead, so anything appended to
     page.css would silently miss half the site.

  2. A CLEAN dist/. Copies each page plus only the assets that page actually
     references, resolved from its own <script src> and <link href> tags. The
     repository holds a 26 MB download cache, fifteen verification scripts, the
     data build scripts and an .attic of superseded code -- none of which may
     ship. The rule is an ALLOWLIST built from the pages themselves, not a
     denylist of things to skip, because a denylist silently ships whatever it
     forgot.

The ORDER of the course comes from index.html, which already holds it. Nothing
here re-states the running order, so the contents page and the nav cannot
disagree.
"""
from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
# GitHub Pages can publish a branch's ROOT or /docs and nothing else -- not an
# arbitrary folder -- so the bundle is built into docs/. That constraint is the
# whole reason for the name: it lets Pages serve this with no CI workflow at
# all. docs/README.md states that the directory is generated.
DIST = ROOT / "docs"

NAV_BEGIN = "<!-- NAV:BEGIN generated by data/build_site.py — do not hand-edit -->"
NAV_END = "<!-- NAV:END -->"

# Never copied, whatever a page might appear to reference.
FORBIDDEN = re.compile(r"(^|/)(\.attic|data|docs|dist|__pycache__)(/|$)|\.py$")


# --------------------------------------------------------------- the manifest
def manifest() -> list[dict]:
    """The running order, read from the contents page — the single source."""
    s = (ROOT / "index.html").read_text(encoding="utf-8")
    out = []
    for m in re.finditer(
        r'<li><a href="([a-z]+\.html)">\s*'
        r'<span class="n">([^<]+)</span>\s*'
        r'<span class="t">([^<]+?)\s*<span class="d">',
        s,
    ):
        out.append(dict(href=m.group(1), num=m.group(2).strip(),
                        title=re.sub(r"\s+", " ", m.group(3)).strip()))
    if not out:
        raise SystemExit("could not read the running order from index.html")
    return out


# --------------------------------------------------------------------- nav CSS
NAV_CSS = """/* GENERATED by data/build_site.py — do not hand-edit.
   The nav's own stylesheet. It cannot live in page.css: six of the twelve
   pages predate that file and carry inline <style> blocks, so half the site
   would miss it. Every colour carries a literal fallback so the bar still
   renders if tokens.css is absent. */
.sitenav {
  position: sticky; top: 0; z-index: 60;
  display: flex; align-items: center; gap: 18px;
  padding: 10px 22px;
  background: rgba(5, 7, 13, 0.92);
  border-bottom: 1px solid var(--line, rgba(140, 170, 210, 0.14));
  backdrop-filter: blur(8px);
  font-family: var(--mono, ui-monospace, "SF Mono", Menlo, monospace);
  font-size: 11px; letter-spacing: 0.06em;
}
.sitenav a { text-decoration: none; }
.sn-home {
  font-weight: 700; letter-spacing: 0.16em;
  color: var(--fg, #e2eefc); opacity: 0.9; white-space: nowrap;
}
.sn-home:hover { opacity: 1; color: var(--cyan, #8ae1f5); }
.sn-pos {
  color: var(--cyan, #8ae1f5); opacity: 0.85; white-space: nowrap;
  padding-left: 14px; border-left: 1px solid rgba(140, 170, 210, 0.18);
}
.sn-count { color: var(--dim, rgba(150, 180, 220, 0.5)); white-space: nowrap; }
.sn-links { margin-left: auto; display: flex; align-items: center; gap: 14px;
            min-width: 0; }
.sn-prev, .sn-next {
  color: var(--dim, rgba(150, 180, 220, 0.62));
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  max-width: 30ch;
}
.sn-prev:hover, .sn-next:hover { color: var(--cyan, #8ae1f5); }
.sn-next { font-weight: 600; color: rgba(190, 214, 240, 0.85); }
@media (max-width: 860px) {
  .sitenav { gap: 10px; padding: 8px 14px; font-size: 10px; }
  .sn-prev { display: none; }
  .sn-next { max-width: 18ch; }
}
@media (prefers-reduced-motion: reduce) {
  .sitenav { backdrop-filter: none; background: #05070d; }
}
"""


def nav_html(order: list[dict], i: int | None) -> str:
    """i is the index in `order`, or None for the contents page itself."""
    n = len(order)
    if i is None:
        first = order[0]
        body = (
            f'<a class="sn-home" href="index.html">UDJ · SEEING THE STATISTICS</a>'
            f'<span class="sn-count">{n} visuals · every figure checked against '
            f'its data</span>'
            f'<span class="sn-links">'
            f'<a class="sn-next" href="{first["href"]}">start · {first["num"]} '
            f'{first["title"]} →</a></span>'
        )
    else:
        cur = order[i]
        links = ""
        if i > 0:
            p = order[i - 1]
            links += (f'<a class="sn-prev" href="{p["href"]}">← {p["num"]} '
                      f'{p["title"]}</a>')
        if i < n - 1:
            q = order[i + 1]
            links += (f'<a class="sn-next" href="{q["href"]}">{q["num"]} '
                      f'{q["title"]} →</a>')
        body = (
            f'<a class="sn-home" href="index.html">← UDJ</a>'
            f'<span class="sn-pos">{cur["num"]} · {cur["title"]}</span>'
            f'<span class="sn-count">{i + 1} of {n}</span>'
            f'<span class="sn-links">{links}</span>'
        )
    return f'{NAV_BEGIN}\n<nav class="sitenav">{body}</nav>\n{NAV_END}'


# ------------------------------------------------------------------- injection
def inject(path: Path, nav: str) -> str:
    s = path.read_text(encoding="utf-8")

    # the nav block, replaced if already present so re-runs are idempotent
    if NAV_BEGIN in s:
        s = re.sub(re.escape(NAV_BEGIN) + r".*?" + re.escape(NAV_END), nav, s,
                   count=1, flags=re.S)
    else:
        m = re.search(r"^<body>\s*$", s, re.M)
        if not m:
            raise SystemExit(f"{path.name}: no plain <body> line to inject after")
        s = s[:m.end()] + "\n" + nav + s[m.end():]

    # the nav stylesheet, linked last so it wins over a page's own rules
    if 'href="nav.css"' not in s:
        m = re.search(r'(<link rel="stylesheet" href="[^"]+">)(?![\s\S]*'
                      r'<link rel="stylesheet")', s)
        if m:
            s = s[:m.end()] + '\n<link rel="stylesheet" href="nav.css">' + s[m.end():]
        else:
            s = s.replace("</head>", '<link rel="stylesheet" href="nav.css">\n</head>', 1)
    return s


def assets_of(html: str) -> list[str]:
    """Local files a page loads. Allowlist: only what the page names itself."""
    found = []
    for m in re.finditer(r'<(?:script|link)[^>]*?(?:src|href)="([^"]+)"', html):
        u = m.group(1)
        if u.startswith(("http://", "https://", "//", "#", "data:", "mailto:")):
            continue
        if u.endswith(".html"):          # a sibling page, handled separately
            continue
        if FORBIDDEN.search(u) or ".." in u:
            raise SystemExit(f"a page references a forbidden path: {u!r}")
        found.append(u)
    return found


def main() -> None:
    order = manifest()
    print(f"running order, read from index.html — {len(order)} pages:")
    for i, e in enumerate(order):
        print(f"  {i + 1:>2}. {e['num']:<6} {e['href']:<18} {e['title']}")

    (ROOT / "nav.css").write_text(NAV_CSS, encoding="utf-8")
    print("\nwrote nav.css")

    # ---- inject into the sources, idempotently
    pages = [("index.html", None)] + [(e["href"], i) for i, e in enumerate(order)]
    updated: dict[str, str] = {}
    for href, i in pages:
        p = ROOT / href
        if not p.exists():
            raise SystemExit(f"{href} is in the running order but does not exist")
        updated[href] = inject(p, nav_html(order, i))
        p.write_text(updated[href], encoding="utf-8")
    print(f"nav injected into {len(pages)} pages (idempotent — re-runnable)")

    # ---- assemble dist from an ALLOWLIST of what the pages name
    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir()
    needed: set[str] = {"nav.css"}
    for href, _ in pages:
        needed.update(assets_of(updated[href]))
    for href, _ in pages:
        shutil.copy2(ROOT / href, DIST / href)
    for a in sorted(needed):
        src = ROOT / a
        if not src.exists():
            raise SystemExit(f"a page references {a!r}, which does not exist")
        (DIST / a).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, DIST / a)

    total = sum(f.stat().st_size for f in DIST.rglob("*") if f.is_file())
    print(f"\ndocs/ — {len(pages)} pages + {len(needed)} assets, "
          f"{total / 1024:.0f} KB total")
    for f in sorted(DIST.rglob("*")):
        if f.is_file():
            print(f"  {f.stat().st_size:>8,}  {f.relative_to(DIST)}")

    (DIST / "manifest.json").write_text(json.dumps(
        dict(pages=[dict(order=i + 1, **e) for i, e in enumerate(order)],
             assets=sorted(needed), bytes=total), indent=1), encoding="utf-8")

    (DIST / "README.md").write_text(f"""# Seeing the statistics — deployable bundle

{len(order)} interactive statistics visuals plus a contents page. Generated by
`data/build_site.py`; do not edit anything here by hand, it is overwritten.

The directory is called `docs/` because GitHub Pages can publish a branch's root
or `/docs` and nothing else. The name is that convention, not a description.

## Deploying

Entirely static — no server-side anything, no build step at the far end, and
every internal link is relative, so it works from a subdirectory as well as a
domain root.

    # GitHub Pages — repository Settings > Pages > Source: branch, folder /docs
    # (no workflow needed; committing this folder is the deploy)

    # any other static host
    aws s3 sync . s3://your-bucket/ --delete       # S3 + CloudFront
    netlify deploy --prod --dir .                  # Netlify

Locally:

    python3 -m http.server 8000 --bind 127.0.0.1

## One external dependency

The pages load **Manrope** and **Inter** from Google Fonts. Everything else is
self-contained. Without network access the type falls back to a system stack and
the layout still holds, but if you need a fully offline bundle, vendor the two
font files and rewrite the `<link>` tags.

## What is deliberately absent

The source repository also holds a 26 MB dataset download cache, the scripts
that measure the data, and {len(list(ROOT.glob('verify_*.py')))} verification
scripts that re-derive every published figure from its raw source. None of that
is needed to serve the site, so none of it is here. `docs/` is assembled from an
allowlist built by reading each page's own asset tags — not by copying the
repository and deleting things.
""", encoding="utf-8")
    print("\nwrote docs/manifest.json and docs/README.md")


if __name__ == "__main__":
    main()
